/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_holo_encrypt_MailAccount */

#ifndef _Included_com_holo_encrypt_MailAccount
#define _Included_com_holo_encrypt_MailAccount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_holo_encrypt_MailAccount
 * Method:    getMailAccount
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_holo_encrypt_MailAccount_getMailAccount
  (JNIEnv *, jclass);

/*
 * Class:     com_holo_encrypt_MailAccount
 * Method:    getMailPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_holo_encrypt_MailAccount_getMailPassword
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
